runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.10.6"
        channel: 'stable'
        cache: true

    - name: Get dependencies
      shell: bash
      run: flutter pub get