name: anywhere_character_viewer
description: Simple project to display character list
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: 3.10.6

dependencies:
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^4.0.6
  dual_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  logger: ^2.0.1
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  dependency_validator: ^3.2.2
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  http_mock_adapter: ^0.3.3
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter_gen:
  output: lib/core/ui/tokens/assets_gen/
  line_length: 120

  integrations:
    flutter_svg: true

  assets:
    outputs:
      class_name: CoreAssets

flutter:
  assets:
    - assets/images/
    - assets/images/splash/
  uses-material-design: true
  generate: true

flutter_native_splash:
  background_image: "assets/images/splash/splash.jpeg"
  android_12:

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app-icon.png"