name: Run analyzer

on:
  push:
    branches: [ "main", "release/**" ]
  pull_request:
    branches: [ "main", "release/**" ]

  workflow_dispatch:

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup_flutter

      - name: Run analyzer
        run: flutter analyze